/**
 * Inertia Electric Motors Solutions - Centralized Data Store
 * Products: 27 authentic catalogue motors + 5 supporting equipment items
 * Images: local /images/products/ (authentic photography)
 */

const COMPANY_INFO = {
  name: "Inertia Electric Motors Solutions",
  shortName: "Inertia",
  tagline: "Industrial Motors, Drives & Power Transmission Solutions",
  subTagline: "Authorized Distributor & Technical Partner for Plant Operations",
  legalType: "Sole Proprietorship",
  address: "Badangpet, Hyderabad, Telangana, India - 500058",
  phones: ["+91 93816 19344", "+91 89195 02422"],
  primaryPhone: "+91 93816 19344",
  secondaryPhone: "+91 89195 02422",
  whatsappNumber: "919381619344",
  emails: ["inertia.motors01@gmail.com"],
  primaryEmail: "inertia.motors01@gmail.com",
  workingHours: "Monday to Saturday, 9:00 AM - 7:00 PM IST",
  registrations: [
    { label: "GST Registered", code: "GSTIN Verified" },
    { label: "MSME Registered", code: "Govt. of India Certified" },
    { label: "ISO Compliant Quality", code: "Industrial Standard" }
  ]
};

const STATS_DATA = [
  { value: 27, suffix: "+", label: "Motor Products", desc: "Authentic Inertia catalogue" },
  { value: 10, suffix: "", label: "Global Brands", desc: "ABB, Siemens, Kirloskar & more" },
  { value: 24, suffix: "h", label: "Quote Turnaround", desc: "Technical commercial proposals" },
  { value: 500, suffix: "+", label: "Plants Served", desc: "Across Hyderabad & Telangana" }
];

const BRANDS_DATA = [
  { name: "ABB", tag: "Heavy Industry & Drives", country: "Switzerland" },
  { name: "Siemens", tag: "Precision & Automation", country: "Germany" },
  { name: "Kirloskar", tag: "Rugged Indian Heritage", country: "India" },
  { name: "Bharat Bijlee", tag: "Industrial Efficiency", country: "India" },
  { name: "Marathon", tag: "Severe Duty Motors", country: "USA" },
  { name: "Havells", tag: "Energy Efficient Tech", country: "India" },
  { name: "CG Power", tag: "High Voltage & HT Drives", country: "India" },
  { name: "WEG", tag: "Global Motor Power", country: "Brazil" },
  { name: "TECO", tag: "Heavy Duty & Mining", country: "Taiwan" },
  { name: "Bonfiglioli", tag: "Planetary & Geared Drives", country: "Italy" }
];

const ASSET_PHOTOS = {
  pump:  "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=900&q=80",
  power: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=80",
  panel: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=900&q=80"
};

const PRODUCTS_DATA = [

  // GEARED MOTORS

  {
    id: "inline-helical-geared-motors",
    name: "Inline Helical Geared Motors",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "0.18 kW to 200 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "Output: 0.5 to 300 RPM",
    mounting: "Foot (B3), Flange (B5), Shaft Mounted",
    enclosure: "Cast Iron Housing, TEFC Motor",
    protection: "IP55",
    insulation: "Class F",
    efficiency: ">= 95%",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Conveyors, mixers, agitators, elevators, packaging lines",
    desc: "Compact inline helical geared motor with coaxial shafts - high torque, 95%+ gear efficiency, quiet operation for conveyors and mixers.",
    chips: ["Coaxial Shaft", "95%+ Efficiency", "TEFC Motor", "High Torque", "Quiet Operation"],
    bg: "images/products/inline-helical-geared-motors-250x250.jpg",
    featured: true, popular: true,
    popularSpec: "Inline Helical - Foot Mounted - IP55"
  },
  {
    id: "cycloidal-gear-motor",
    name: "Cycloidal Gear Motor",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "", poles: "",
    rpm: "High reduction ratio output",
    mounting: "Flange or foot as required",
    enclosure: "Compact cycloidal housing",
    protection: "IP55", insulation: "Class F",
    efficiency: "High mechanical efficiency",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Robotics, automation, precision positioning, indexing tables",
    desc: "Zero-backlash cycloidal speed reducer with integrated motor - ideal for robotics, automation, and precision positioning. Compact high-torque speed reducer using eccentric shaft design.",
    chips: ["Zero Backlash", "High Reduction Ratio", "Shock Resistant", "Precision", "Compact"],
    bg: "images/products/cycloidal-gear-motor-250x250.jpg",
    featured: false, popular: false
  },
  {
    id: "right-angle-helical-worm-geared-motors",
    name: "Right Angle Helical Worm Geared Motors",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "0.12 kW to 90 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "Output: 1 to 300 RPM",
    mounting: "Foot, Flange, Shaft Mount, Torque Arm",
    enclosure: "Aluminium or Cast Iron Housing",
    protection: "IP55 / IP65", insulation: "Class F",
    efficiency: "Up to 85% (worm stage)",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Material handling, packaging machinery, conveyors, food processing",
    desc: "Right-angle worm helical gear motor - compact build, excellent for material handling and packaging lines. Space-saving 90-degree shaft arrangement with wide gear ratio range.",
    chips: ["Right Angle Output", "Worm Helical", "Compact Build", "Wide Ratio Range", "IP55/IP65"],
    bg: "images/products/right-angle-helical-worm-geared-motors-250x250.jpg",
    featured: false, popular: true,
    popularSpec: "Right Angle - Worm Helical - IP55"
  },
  {
    id: "parallel-shaft-geared-motor",
    name: "Parallel Shaft Geared Motor",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "0.18 kW to 160 kW",
    poles: "2, 4, 6 Pole",
    rpm: "Output: 5 to 400 RPM",
    mounting: "Foot (B3), Flange (B5), Torque Arm",
    enclosure: "Rigid Cast Iron Casing",
    protection: "IP55", insulation: "Class F",
    efficiency: "> 96% gear efficiency",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Conveyors, agitators, belt drives, screw feeders",
    desc: "Parallel shaft helical gear motor - compact design with high gear ratio range for conveyors and agitators. Ideal for medium-to-high torque applications.",
    chips: ["Parallel Shaft", "High Ratio Range", "96%+ Efficiency", "Helical Gears", "Heavy Duty"],
    bg: "images/products/parallel-shaft-geared-motor-250x250.jpg",
    featured: false, popular: false
  },
  {
    id: "bevel-helical-geared-motor",
    name: "Bevel Helical Geared Motor",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "0.37 kW to 200 kW",
    poles: "2, 4, 6 Pole",
    rpm: "Output: 1 to 450 RPM",
    mounting: "Foot, Flange, Shaft Mounted with Shrink Disc",
    enclosure: "Heavy Cast Iron Casing",
    protection: "IP55 / IP65", insulation: "Class F",
    efficiency: "Up to 98%",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Mixers, elevators, conveyors, agitators, bucket chains",
    desc: "Right-angle bevel helical gear motor - up to 98% efficiency, low noise, ideal for mixers, elevators, and conveyors. High torque output in a compact right-angle form.",
    chips: ["Bevel Helical", "Right Angle", "98% Efficiency", "Low Noise", "High Torque"],
    bg: "images/products/bevel-helical-geared-motor-250x250.jpg",
    featured: true, popular: true,
    popularSpec: "Bevel Helical - Right Angle - 98% Efficiency"
  },
  {
    id: "helical-dc-electric-geared-motor",
    name: "Helical DC Electric Geared Motor",
    category: "geared-motors",
    categoryLabel: "Geared Motors",
    powerRange: "", poles: "",
    rpm: "Variable speed output",
    mounting: "Foot or Flange Mounted",
    enclosure: "Compact helical gearhead with DC motor",
    protection: "IP44 / IP55", insulation: "Class F",
    efficiency: "High mechanical efficiency",
    voltage: "DC supply as specified",
    application: "Variable-speed industrial drives, positioning systems, automation",
    desc: "DC-powered helical gear motor combining torque and compact form - ideal for variable-speed industrial drives. Integrates helical gearhead with DC motor for precise speed control.",
    chips: ["DC Motor", "Helical Gears", "Variable Speed", "Compact", "Precise Control"],
    bg: "images/products/helical-dc-electric-geared-motor-250x250.jpg",
    featured: false, popular: false
  },

  // AC MOTORS

  {
    id: "squirrel-cage-induction-motor",
    name: "Squirrel Cage Induction Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.18 kW to 375 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B3 Foot, B5 Flange, B35 Foot-Flange, B14 Face",
    enclosure: "TEFC (Totally Enclosed Fan Cooled) Cast Iron / Aluminium",
    protection: "IP55",
    insulation: "Class F (Temp Rise Class B)",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Fans, pumps, compressors, conveyors, crushing, manufacturing",
    desc: "IE2/IE3 three-phase squirrel cage induction motors, 0.18-375 kW, IEC standard frames - the industrial workhorse for continuous duty across all industries.",
    chips: ["IE2 / IE3", "TEFC", "IEC Standard", "Cast Iron", "0.18 to 375 kW"],
    bg: "images/products/squirrel-cage-motors-250x250.webp",
    featured: true, popular: true,
    popularSpec: "7.5 kW - 4 Pole - B3 Foot - IP55 - IE3"
  },
  {
    id: "reluctance-synchronous-motor",
    name: "Reluctance Synchronous Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "7.5 kW (example: TCYP160M-1000)",
    poles: "Configured per speed requirement",
    rpm: "Synchronous speed (VFD controlled)",
    mounting: "B3 Foot, B5 Flange",
    enclosure: "TEFC",
    protection: "IP55", insulation: "Class F",
    efficiency: "High efficiency frequency variable operation",
    voltage: "415V, 50 Hz (VFD compatible)",
    application: "Industrial processes requiring precise speed control, textile, paper, pumps",
    desc: "Variable-frequency synchronous reluctance motor - high efficiency and precision speed control for industrial processes. No permanent magnets, robust and cost-effective synchronous operation.",
    chips: ["Synchronous", "VFD Compatible", "High Efficiency", "Precise Speed", "No Magnets"],
    bg: "images/products/tcyp160m-1000-7-5kw-frequency-variable-reluctance-synchronous-ac-electric-motor-250x250.png",
    featured: false, popular: false
  },
  {
    id: "permanent-magnet-synchronous-motor",
    name: "Permanent Magnet Synchronous Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "",
    poles: "Multi-pole permanent magnet rotor",
    rpm: "Synchronous (VFD driven)",
    mounting: "Flange or Foot Mounted",
    enclosure: "TEFC / IP rated enclosure",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE4 / IE5 Super Premium",
    voltage: "VFD powered, configurable",
    application: "Servo drives, precision machinery, compressors, high-efficiency pumps",
    desc: "High-efficiency permanent magnet synchronous motor - superior power density and low heat generation for servo drives. IE4/IE5 efficiency levels with compact rotor design.",
    chips: ["IE4 / IE5", "Permanent Magnet", "High Power Density", "Low Heat", "Compact Rotor"],
    bg: "images/products/permanent-magnet-synchronous-motor-250x250.avif",
    featured: true, popular: false
  },
  {
    id: "wound-rotor-induction-motor",
    name: "Wound Rotor Induction Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "",
    poles: "4, 6, 8 Pole",
    rpm: "Adjustable via external rotor resistance",
    mounting: "B3 Foot Mounted",
    enclosure: "TEFC / SPDP",
    protection: "IP44 / IP55",
    insulation: "Class F / Class H",
    efficiency: "High starting torque efficiency",
    voltage: "415V 3-Phase, 50 Hz",
    application: "High inertia loads, crushers, mills, compressors, hoists",
    desc: "Three-phase wound rotor asynchronous AC motor - smooth starting and adjustable speed control for high-inertia loads. External rotor resistance provides controlled acceleration.",
    chips: ["Wound Rotor", "3-Phase Async", "High Inertia Loads", "Smooth Start", "Speed Control"],
    bg: "images/products/wound-rotor-induction-motor-3-phase-asynchronous-ac-motor-250x250.avif",
    featured: false, popular: false
  },
  {
    id: "slip-ring-induction-motor",
    name: "Slip Ring Induction Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "2.2 kW to 315 kW",
    poles: "6, 8, 10 Pole",
    rpm: "600 to 1000 RPM",
    mounting: "B3 Foot Mounted Heavy Base",
    enclosure: "TEFC or SPDP",
    protection: "IP55 (TEFC) / IP23 (SPDP)",
    insulation: "Class F / Class H",
    efficiency: "High starting torque duty",
    voltage: "415V Stator, External Rotor Resistance",
    application: "Overhead cranes, winches, heavy crushers, steel rolling mills",
    desc: "Wound rotor slip ring induction motor - high starting torque for crushers, mills, and heavy-load industrial applications. Low inrush current with external resistance control.",
    chips: ["Slip Ring", "High Starting Torque", "Low Inrush", "Crane Duty", "TEFC/SPDP"],
    bg: "images/products/slip-ring-induction-motor-250x250.jpeg",
    featured: true, popular: true,
    popularSpec: "11 kW - 6 Pole - S4 40% Duty - TEFC"
  },
  {
    id: "foot-mounted-b3-ac-motor",
    name: "Foot Mounted B3 AC Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.12 kW to 355 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B3 Foot Mounted (IEC Standard)",
    enclosure: "TEFC Cast Iron / Aluminium Frame",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "General industrial machinery, pumps, fans, compressors, conveyors",
    desc: "IEC standard B3 foot-mounted AC motor - robust cast iron frame, flexible base mounting for all industrial applications. Most versatile and common mounting configuration.",
    chips: ["B3 Foot Mounted", "IEC Standard", "Cast Iron Frame", "TEFC", "Universal Use"],
    bg: "images/products/foot-mounted-b3-ac-motor-250x250.jpg",
    featured: false, popular: true,
    popularSpec: "B3 Foot - 5.5 kW - 4 Pole - IP55"
  },
  {
    id: "flange-mounted-ac-motors",
    name: "Flange Mounted AC Motors",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.12 kW to 250 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B5 Flange Mounted (IEC Standard)",
    enclosure: "TEFC Cast Iron / Aluminium",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Gearbox coupling, pump drives, space-constrained installations",
    desc: "B5 flange-mounted AC motors for space-efficient installations - direct coupling to gearboxes and pumps. Eliminates misalignment through integral flange mounting.",
    chips: ["B5 Flange Mounted", "Direct Coupling", "Space Saving", "IEC Standard", "IE2/IE3"],
    bg: "images/products/flangr-mounted-ac-motors-250x250.jpg",
    featured: false, popular: false
  },
  {
    id: "face-mounted-ac-motors",
    name: "Face Mounted AC Motors",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.12 kW to 90 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B14 Face Mounted (IEC Standard)",
    enclosure: "TEFC Aluminium / Cast Iron",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Tight space installations, gearboxes, pump coupling, robotics",
    desc: "Face-mounted (B14) compact AC motors - ideal for tight spaces and direct gear or pump coupling. Smaller face flange for compact machinery integration.",
    chips: ["B14 Face Mounted", "Compact", "Direct Mount", "IEC Standard", "Aluminium Frame"],
    bg: "images/products/face-mounted-ac-motors-250x250.jpeg",
    featured: false, popular: false
  },
  {
    id: "foot-cum-flange-mounted-ac-motor-b35",
    name: "Foot Cum Flange Mounted AC Motor B35",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.18 kW to 315 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B35 Foot and Flange Combined (IEC Standard)",
    enclosure: "TEFC Cast Iron",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Flexible installation requirements, machinery with multiple mounting points",
    desc: "Versatile B35 foot and flange dual-mount AC motor - flexible installation options for any industrial setup. Combines both B3 foot and B5 flange mounting in a single motor.",
    chips: ["B35 Dual Mount", "Foot + Flange", "Versatile", "Cast Iron", "IEC Standard"],
    bg: "images/products/cumouy-250x250.png",
    featured: false, popular: false
  },
  {
    id: "alternating-current-motor",
    name: "Alternating Current Motor",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "0.12 kW to 375 kW",
    poles: "2, 4, 6, 8 Pole",
    rpm: "750 to 3000 RPM",
    mounting: "B3, B5, B14, B35 as required",
    enclosure: "TEFC Cast Iron / Aluminium",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Fans, pumps, compressors, conveyors, general industrial machinery",
    desc: "General-purpose AC induction motor - reliable and cost-effective for fans, pumps, compressors, and conveyors. Standard IEC construction for universal industrial use.",
    chips: ["General Purpose", "AC Induction", "IE2 / IE3", "IEC Frame", "Multi-Mounting"],
    bg: "images/products/screenshot-20251231-142045-png-250x250.png",
    featured: false, popular: false
  },
  {
    id: "cooling-tower-motors",
    name: "Cooling Tower Motors",
    category: "ac-motors",
    categoryLabel: "AC Motors",
    powerRange: "1.5 kW to 37 kW",
    poles: "6, 8, 12 Pole",
    rpm: "500 to 1000 RPM",
    mounting: "B5 Flange Vertical Shaft Down / B3 Foot",
    enclosure: "Totally Enclosed Surface Cooled (TESC/TEFC)",
    protection: "IP55 / IP65 Tropicalized",
    insulation: "Class F with Moisture-Resistant Varnish",
    efficiency: "IE2 / IE3",
    voltage: "415V, 50 Hz",
    application: "Cooling towers, evaporative coolers, wet and humid environments",
    desc: "Moisture-resistant motors designed for cooling tower environments - corrosion-proof insulation and sealed bearings. Specialized for 100% relative humidity and chemical water exposure.",
    chips: ["Wet Duty", "IP55/IP65", "Tropicalized", "Double Lip Seal", "Corrosion Proof"],
    bg: "images/products/cooling-tower-motors-250x250.jpg",
    featured: false, popular: true,
    popularSpec: "5.5 kW - 6 Pole - Wet Duty - IP55 Flange"
  },

  // BRAKE MOTORS

  {
    id: "ac-brake-motor",
    name: "AC Brake Motor",
    category: "brake-motors",
    categoryLabel: "Brake Motors",
    powerRange: "0.18 kW to 45 kW",
    poles: "4, 6, 8 Pole",
    rpm: "750 to 1500 RPM",
    mounting: "B3 Foot / B5 Flange",
    enclosure: "TEFC with Electromagnetic Disc Brake",
    protection: "IP54 / IP55",
    insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V 3-Phase with 190V DC Brake Rectifier",
    application: "Overhead cranes, hoists, machine tools, conveyors, automated packaging",
    desc: "AC brake motor with fail-safe electromagnetic disc brake - reliable emergency stopping for overhead cranes and hoists. Instant stop-start with fast response braking.",
    chips: ["AC Brake Motor", "Electromagnetic Brake", "Fail-Safe", "Fast Stop", "IE2/IE3"],
    bg: "images/products/ac-brake-motor-250x250.jpg",
    featured: false, popular: true,
    popularSpec: "AC Brake - 5.5 kW - 4 Pole - IP55"
  },
  {
    id: "inverter-duty-brake-motor",
    name: "Inverter Duty Brake Motor",
    category: "brake-motors",
    categoryLabel: "Brake Motors",
    powerRange: "0.18 kW to 45 kW",
    poles: "4, 6 Pole",
    rpm: "750 to 1500 RPM",
    mounting: "B3 Foot / B5 Flange",
    enclosure: "TEFC with Integrated Electromagnetic Brake",
    protection: "IP55",
    insulation: "Class F / Class H (VFD rated)",
    efficiency: "IE2 / IE3",
    voltage: "415V 3-Phase VFD output rated",
    application: "Cranes, hoists, automation, precise positioning, VFD-controlled systems",
    desc: "VFD-compatible brake motor with integrated electromagnetic brake - precise stopping for cranes, hoists, and automation. Reinforced insulation for inverter-duty operation.",
    chips: ["VFD Compatible", "Inverter Duty", "Electromagnetic Brake", "Precise Stop", "IP55"],
    bg: "images/products/inverter-duty-brake-motor-250x250.jpg",
    featured: true, popular: true,
    popularSpec: "Inverter Duty - 7.5 kW - 4 Pole - VFD + Brake"
  },
  {
    id: "dc-brake-motors",
    name: "DC Brake Motor",
    category: "brake-motors",
    categoryLabel: "Brake Motors",
    powerRange: "", poles: "",
    rpm: "Rated motor speed with brake hold",
    mounting: "B3 Foot / B5 Flange",
    enclosure: "TEFC with DC Electromagnetic Brake",
    protection: "IP54 / IP55", insulation: "Class F",
    efficiency: "Standard",
    voltage: "DC supply as specified",
    application: "Conveyor systems, positioning machines, automated handling",
    desc: "DC brake motor with fail-safe electromagnetic braking - precise hold and stop for positioning and conveyor systems. DC braking provides quick and consistent stopping performance.",
    chips: ["DC Brake", "Fail-Safe", "Electromagnetic", "Precise Hold", "Positioning"],
    bg: "images/products/dc-brake-motors-250x250.jpg",
    featured: false, popular: false
  },
  {
    id: "flameproof-brake-motor",
    name: "Flameproof Brake Motor",
    category: "brake-motors",
    categoryLabel: "Brake Motors",
    powerRange: "0.37 kW to 45 kW",
    poles: "2, 4, 6 Pole",
    rpm: "1000 to 3000 RPM",
    mounting: "B3 Foot / B5 Flange",
    enclosure: "Heavy Cast Iron Ex d IIA/IIB with Integral Brake",
    protection: "IP55 / IP65 Zone 1 and Zone 2",
    insulation: "Class F with Dual Thermistors",
    efficiency: "IE2 / IE3 FLP",
    voltage: "415V +/- 10%, 50 Hz",
    application: "Hazardous areas: oil refineries, chemical plants, pharma, mines",
    desc: "ATEX-certified flameproof brake motor for hazardous areas - explosion-proof casing with integrated holding brake. PESO and CMRI certified for Zone 1 and Zone 2 environments.",
    chips: ["ATEX / Ex d", "Flameproof", "PESO Certified", "Zone 1 and 2", "Integral Brake"],
    bg: "images/products/flameproof-brake-motor-250x250.avif",
    featured: true, popular: true,
    popularSpec: "7.5 kW - 4 Pole - Ex d IIB T4 - Flameproof Brake"
  },
  {
    id: "gear-brake-motor",
    name: "Gear Brake Motor",
    category: "brake-motors",
    categoryLabel: "Brake Motors",
    powerRange: "", poles: "",
    rpm: "Reduced output speed with braking",
    mounting: "Foot or Flange Mounted",
    enclosure: "Integrated gearhead + motor + brake",
    protection: "IP55", insulation: "Class F",
    efficiency: "Combined gear and motor efficiency",
    voltage: "415V 3-Phase, 50 Hz",
    application: "Material handling, conveyors, hoists, automated production lines",
    desc: "Integrated gear and electromagnetic brake motor - precise stopping and high torque for material handling systems. Three-in-one: gearbox, motor, and brake in a single compact unit.",
    chips: ["Gear + Motor + Brake", "Electromagnetic Brake", "High Torque", "Compact Unit", "Precise Stop"],
    bg: "images/products/gear-brake-motor-250x250.png",
    featured: false, popular: false
  },

  // DC MOTORS

  {
    id: "compound-dc-motor",
    name: "Compound DC Motor",
    category: "dc-motors",
    categoryLabel: "DC Motors",
    powerRange: "",
    poles: "Compound wound (shunt + series field)",
    rpm: "Variable (field controlled)",
    mounting: "B3 Foot / as required",
    enclosure: "DPFG or TEFC (DC rated)",
    protection: "IP44 / IP54",
    insulation: "Class F / Class H",
    efficiency: "High torque at variable speed",
    voltage: "DC supply: 110V, 220V, 440V as specified",
    application: "Traction, cranes, hoists, printing machinery, rolling mills",
    desc: "DC compound motor combining shunt and series field windings - excellent torque-speed characteristics for traction and cranes. Handles both constant torque and constant power loads effectively.",
    chips: ["Compound Wound", "Shunt + Series", "DC Motor", "Variable Speed", "High Torque"],
    bg: "images/products/compound-dc-motor-250x250.webp",
    featured: false, popular: false
  },

  // AHU / HVAC MOTORS

  {
    id: "air-handling-unit-motor",
    name: "Air Handling Unit Motor",
    category: "ahu-motors",
    categoryLabel: "AHU Motors",
    powerRange: "0.55 kW to 45 kW",
    poles: "4, 6 Pole",
    rpm: "1000, 1500 RPM",
    mounting: "Foot (B3) / Pad Mounted",
    enclosure: "TEFC Low Noise Aluminium / Cast Iron",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE3 Premium Efficiency",
    voltage: "415V, 50 Hz (VFD Compatible)",
    application: "HVAC air handling units, hospitals, clean rooms, malls, commercial buildings",
    desc: "Specially designed AHU motors for HVAC air handling units - efficient, low-vibration, and built for continuous duty. Ultra-low noise levels for sensitive building environments.",
    chips: ["HVAC Duty", "Ultra Low Noise", "Clean Room Grade", "VFD Compatible", "IE3"],
    bg: "images/products/air-handling-unit-motor-250x250.jpg",
    featured: false, popular: false
  },
  {
    id: "variable-speed-ahu-motors",
    name: "Variable Speed AHU Motors",
    category: "ahu-motors",
    categoryLabel: "AHU Motors",
    powerRange: "0.55 kW to 55 kW",
    poles: "4, 6 Pole",
    rpm: "Variable (VFD controlled)",
    mounting: "Foot (B3) / Pad Mounted",
    enclosure: "TEFC Low Noise Frame",
    protection: "IP55",
    insulation: "Class F (VFD reinforced)",
    efficiency: "IE3 - Energy efficient at variable speed",
    voltage: "415V, 50 Hz (VFD driven)",
    application: "Variable-volume HVAC, energy-efficient ventilation systems",
    desc: "Variable-speed air handling unit motors - energy-efficient and VFD-compatible for HVAC and ventilation systems. Designed for wide speed range operation without overheating.",
    chips: ["Variable Speed", "VFD Compatible", "Energy Efficient", "HVAC Duty", "IE3"],
    bg: "images/products/variable-speed-ahu-motors-250x250.avif",
    featured: false, popular: false
  },
  {
    id: "belt-drive-ahu-motor",
    name: "Belt Drive AHU Motor",
    category: "ahu-motors",
    categoryLabel: "AHU Motors",
    powerRange: "1.1 kW to 37 kW",
    poles: "4, 6 Pole",
    rpm: "1000 to 1500 RPM",
    mounting: "Foot (B3), Extended Shaft for Belt Pulley",
    enclosure: "TEFC with Extended Shaft",
    protection: "IP55", insulation: "Class F",
    efficiency: "IE2 / IE3",
    voltage: "415V, 50 Hz",
    application: "Belt-driven AHU fans, large ventilation units, industrial HVAC",
    desc: "Belt-drive AHU motor with extended shaft - smooth belt operation for large air handling and ventilation units. Extended shaft accommodates pulleys and belt drives directly.",
    chips: ["Belt Drive", "Extended Shaft", "AHU Duty", "IP55", "IE2/IE3"],
    bg: "images/products/belt-drive-ahu-motor-250x250.jpg",
    featured: false, popular: false
  },

  // CRANE / SPECIAL DUTY

  {
    id: "crane-duty-motor",
    name: "Crane Duty Motor",
    category: "crane-motors",
    categoryLabel: "Crane Duty Motors",
    powerRange: "2.2 kW to 315 kW",
    poles: "6, 8, 10 Pole",
    rpm: "600 to 1000 RPM",
    mounting: "B3 Foot Mounted Heavy Base",
    enclosure: "TEFC or SPDP (Screen Protected Drip Proof)",
    protection: "IP55 (TEFC) / IP23 (SPDP)",
    insulation: "Class F / Class H",
    efficiency: "Heavy Starting Torque - S3/S4 Duty",
    voltage: "415V Stator, External Rotor Resistance Control",
    application: "Overhead cranes, hoists, EOT cranes, winches, bridge cranes",
    desc: "Heavy-duty slipring motor designed for crane and hoist applications - high cyclic duty and robust construction. Withstands frequent start-stop cycles in S3/S4 duty ratings.",
    chips: ["Crane Duty", "S3 / S4 Duty", "40% / 60% CDF", "Slip Ring", "High Cyclic"],
    bg: "images/products/crane-duty-motor-250x250.png",
    featured: true, popular: true,
    popularSpec: "15 kW - 6 Pole - S4 40% Duty - TEFC"
  },

  // SUPPORTING EQUIPMENT

  {
    id: "industrial-pumps",
    name: "Industrial Pumps & Pumping Sets",
    category: "pumps",
    categoryLabel: "Pumps",
    powerRange: "1.5 kW to 250 kW",
    poles: "2, 4 Pole Drives",
    rpm: "1450 and 2900 RPM",
    mounting: "Baseplate Mounted with Flexible Coupling / Monoblock",
    enclosure: "Cast Iron / Bronze / SS316 Impeller and Casing",
    protection: "IP55 Heavy Duty Pumping Motor",
    insulation: "Class F Motor Insulation",
    efficiency: "High Hydraulic Efficiency",
    voltage: "415V, 50 Hz",
    application: "Water supply, irrigation, chemical transfer, fire fighting, boiler feed",
    desc: "Heavy-duty fluid transfer systems including end-suction, horizontal split casing, multistage boiler feed, and fire-fighting hydrant pumps.",
    chips: ["End Suction", "Split Casing", "Monoblock", "Fire Fighting", "Multistage"],
    bg: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=900&q=80",
    featured: true, popular: true,
    popularSpec: "15 kW - 50 m head - 60 m3/hr - End Suction"
  },
  {
    id: "distribution-transformers",
    name: "Industrial Distribution Transformers",
    category: "power",
    categoryLabel: "Power Equipment",
    powerRange: "63 kVA to 5000 kVA",
    poles: "Copper / Aluminium Wound",
    rpm: "Static Power Conversion",
    mounting: "Plinth Mounted with Bi-directional Rollers",
    enclosure: "Hermetically Sealed / Conservator Oil-Immersed (ONAN)",
    protection: "IP54 Cable Boxes / Outdoor Weatherproof",
    insulation: "Class A Mineral Oil / Ester Fluid",
    efficiency: "BIS Energy Level 2 and Level 3 Standard",
    voltage: "11 kV / 33 kV Primary to 433V Secondary",
    application: "Substations, motor control centres, industrial power distribution",
    desc: "High-reliability substation distribution and step-down transformers designed to deliver steady, clean three-phase power to motor control centers.",
    chips: ["Distribution", "Step-Down", "ONAN Cooled", "11kV/433V", "BIS Certified"],
    bg: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=80",
    featured: true, popular: true,
    popularSpec: "250 kVA - 11 kV / 433 V - ONAN Plinth"
  },
  {
    id: "industrial-generators",
    name: "Standby & Prime Power Generators",
    category: "power",
    categoryLabel: "Power Equipment",
    powerRange: "15 kVA to 2000 kVA",
    poles: "4 Pole Synchronous Alternator",
    rpm: "1500 RPM",
    mounting: "Heavy Structural Steel Skid with Anti-Vibration Mounts",
    enclosure: "CPCB-IV+ Acoustic Weatherproof Canopy",
    protection: "IP23 Alternator, IP54 Control Enclosure",
    insulation: "Class H Alternator Insulation",
    efficiency: "Optimized Specific Fuel Consumption",
    voltage: "415V 3-Phase, 0.8 Power Factor",
    application: "Industrial standby power, DG sets for motor-heavy plants",
    desc: "Continuous and standby diesel gensets sized to handle inductive motor starting current surges without voltage dips or plant tripping.",
    chips: ["Standby Power", "Prime Power", "Acoustic Canopy", "Load Matched"],
    bg: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=80",
    featured: false, popular: false
  },
  {
    id: "circuit-breakers",
    name: "Air & Moulded Case Circuit Breakers (ACB / MCCB)",
    category: "power",
    categoryLabel: "Power Equipment",
    powerRange: "16A to 4000A Breaking Capacity",
    poles: "3 Pole / 4 Pole",
    rpm: "Instantaneous Trip and Thermal Magnetic Release",
    mounting: "Fixed / Draw-out Panel Mount",
    enclosure: "High-dielectric Insulated Shell",
    protection: "IP40 Front / IP20 Terminals",
    insulation: "1000V Rated Insulation Voltage",
    efficiency: "Category B - Ics = 100% Icu",
    voltage: "415V / 690V AC",
    application: "Motor protection panels, MCC, distribution boards",
    desc: "Essential electrical protection devices safeguarding motors, busbars, and distribution cables from severe short circuits, overloads, and earth faults.",
    chips: ["ACB", "MCCB", "Motor Protection", "Short Circuit", "Panel Ready"],
    bg: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=900&q=80",
    featured: false, popular: false
  },
  {
    id: "oil-starters",
    name: "Oil-Immersed Motor Starters",
    category: "power",
    categoryLabel: "Power Equipment",
    powerRange: "5 HP to 250 HP",
    poles: "DOL and Star-Delta",
    rpm: "Manual / Push-button Magnetic Trip",
    mounting: "Wall / Floor Stand Mounting",
    enclosure: "Heavy Gauge Sheet Steel Oil Tank",
    protection: "IP54 Weatherproof Oil Tank",
    insulation: "Dielectric Transformer Oil Cooling",
    efficiency: "Zero Arcing on Copper Contacts",
    voltage: "415V 3-Phase",
    application: "Agricultural pumps, stone crushers, flour mills, dusty harsh environments",
    desc: "Heavy-duty oil-cooled motor starters for agricultural pumps, stone crushers, flour mills, and harsh environments where dust would ruin dry contactors.",
    chips: ["Oil Immersed", "Star-Delta", "DOL", "Dustproof Tank", "Heavy Duty"],
    bg: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=900&q=80",
    featured: false, popular: false
  }
];

const INDUSTRIES_DATA = [
  {
    id: "cement",
    name: "Cement & Aggregates",
    icon: "factory",
    operatingEnv: "Extreme airborne abrasive dust, heavy shock loads, high ambient temperatures, 24/7 continuous duty.",
    challenge: "Fine clinker dust enters standard motor cowls, while crusher ball mills generate immense shock torques during rock reduction.",
    solution: "Heavy-duty TEFC Cast Iron IE3/IE4 motors and Crane-duty Slip Ring motors with IP66 labyrinths and reinforced re-greasable bearings.",
    specs: ["IP55/IP66 Protection", "Crane Duty S4", "Cast Iron Frame", "Vibration Monitored"],
    chips: ["IP55/IP66", "Crane duty", "Slip Ring", "Crushers and Kilns"],
    bg: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "crane-motors"
  },
  {
    id: "steel",
    name: "Steel & Metallurgical Plants",
    icon: "anvil",
    operatingEnv: "Intense radiant furnace heat, molten splash risk, frequent rapid reversing, massive torque overloads.",
    challenge: "Hot rolling mills and ladle cranes cause severe thermal stress and continuous cyclical mechanical fatigue.",
    solution: "Class H insulated slip ring crane-duty motors, roller table auxiliary drives, and heavy bevel-helical reduction gearboxes.",
    specs: ["Class H Insulation", "High Starting Torque", "Brake Integration", "Shock Resistance"],
    chips: ["Slip ring", "High torque", "Roller table", "Heavy Gearing"],
    bg: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "crane-motors"
  },
  {
    id: "power-plants",
    name: "Power Generation Plants",
    icon: "zap",
    operatingEnv: "High ambient heat, vibration from turbines, corrosive cooling water, outdoor exposure.",
    challenge: "Cooling tower fan motors and boiler feed pump drives must handle high humidity and continuous 24/7 duty.",
    solution: "Tropicalized IP65 cooling tower motors, moisture-resistant insulation varnish, and sealed bearing arrangements.",
    specs: ["IP65 Tropicalized", "Class F/H Insulation", "Sealed Bearings", "Continuous S1"],
    chips: ["Cooling Tower", "Boiler Feed", "IP65", "24/7 Duty"],
    bg: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "ac-motors"
  },
  {
    id: "food-pharma",
    name: "Food, Pharma & Chemical",
    icon: "flask",
    operatingEnv: "Hygiene zones, chemical wash-down, clean rooms, explosion risk in solvent handling.",
    challenge: "Standard motors corrode in chemical splash zones; FLP variants are needed where solvent vapours accumulate.",
    solution: "Stainless steel shaft motors, flameproof Ex d variants, and IP66 sealed geared motors for hygienic applications.",
    specs: ["Ex d Flameproof", "IP66 Washdown", "SS Shaft Option", "Clean Room Grade"],
    chips: ["Flameproof", "IP66", "Washdown", "Pharma Grade"],
    bg: "https://images.unsplash.com/photo-1559825481-12a05cc00344?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "brake-motors"
  },
  {
    id: "textile",
    name: "Textile & Yarn Mills",
    icon: "layers",
    operatingEnv: "Lint accumulation, humidity, continuous multi-shift operation, precision speed requirements.",
    challenge: "Lint clogs motor cooling fins causing overheating; yarn tension requires precise, stable motor speed.",
    solution: "Totally enclosed TEFC motors with IP55 protection, Class F insulation, and VFD-compatible reluctance synchronous drives.",
    specs: ["TEFC IP55", "VFD Compatible", "Lint Resistant", "Precision Speed"],
    chips: ["TEFC", "Lint Resistant", "VFD", "Synchronous"],
    bg: "https://images.unsplash.com/photo-1558171813-9a0890dfa963?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "ac-motors"
  },
  {
    id: "hvac",
    name: "HVAC & Building Services",
    icon: "wind",
    operatingEnv: "Low ambient noise requirements, clean room grade air, variable load conditions.",
    challenge: "AHU motors in hospitals and malls must be ultra-quiet, vibration-free, and energy efficient across variable speeds.",
    solution: "Dynamically balanced AHU motors with IE3 efficiency, VFD compatibility, and G2.5 vibration grade certification.",
    specs: ["IE3 Efficiency", "Ultra Low Noise", "G2.5 Vibration", "VFD Compatible"],
    chips: ["AHU Duty", "Low Noise", "Clean Room", "VFD"],
    bg: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "ahu-motors"
  },
  {
    id: "mining",
    name: "Mining & Quarrying",
    icon: "mountain",
    operatingEnv: "Underground explosive atmospheres, heavy shock loads, water ingress, gritty abrasive environment.",
    challenge: "Conveyor and crusher drives need flameproof certification and extreme robustness against rock and dust.",
    solution: "Ex d IIB T4 flameproof motors and high-torque slip ring drives with reinforced cast iron frames and IP66 protection.",
    specs: ["Ex d IIB T4", "IP66", "Shock Proof", "Heavy Duty"],
    chips: ["Flameproof", "IP66", "Mining Duty", "Crusher Drive"],
    bg: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "brake-motors"
  },
  {
    id: "water-treatment",
    name: "Water & Wastewater Treatment",
    icon: "droplet",
    operatingEnv: "Outdoor exposure, humid and corrosive chemical atmosphere, submerged or splash-zone installations.",
    challenge: "Pump motors in clarifiers and aeration tanks face chemical splash, humidity, and continuous S1 duty.",
    solution: "IP55/IP65 motors with epoxy-coated frames, moisture-resistant Class F insulation, and corrosion-resistant bearing caps.",
    specs: ["IP55/IP65", "Epoxy Coated", "Corrosion Resistant", "Continuous S1"],
    chips: ["IP65", "Epoxy Frame", "Outdoor Duty", "Pump Drive"],
    bg: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80",
    matchedCategory: "ac-motors"
  }
];
